version: '3.8'
services:
  api:
    build: ./politicians-backend
    container_name: politicians-backend
    ports:
      - '3000:3000'
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
  frontend:
    build: ./politicians-frontend
    container_name: politicians-frontend
    ports:
      - '3010:3010'
    stdin_open: true
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
